### PR TITLE
add Distributions 0.21 to Project.toml

### PR DESCRIPTION
**Pull request by bjarthur**
tests pass with 0.21, but i couldn't get Pkg to update to 0.20.  any idea why?

### CODE REVIEW

**Comment by pkofod** [comment]
I wonder why every version is listed like that. Should we just say `0.18` instead? I think so.

**Comment by ChrisRackauckas** [comment]
It's upper bounding at 0.19 right now.

**Comment by bjarthur** [comment]
not if you do `] add LsqFit` instead of `dev`.  that took me an embarrassingly long time to figure out why!

**Comment by ChrisRackauckas** [comment]
well because that's before the Project.toml, but that's still not a good idea.

**Comment by bjarthur** [comment]
i managed to pin Distributions 0.20 and LsqFit tests pass with it.  so i've added it to Project.toml as well in this PR.  i also removed the inequality in the compat section for the julia version as without an upper bound it won't get [automatically merged](https://discourse.julialang.org/t/announcement-automatic-merging-for-the-general-registry/29961) into the Registry.

i've also added CI testing on "julia 1" in travis, which will use 1.3 now and auto change to 1.4 etc when that is released.

lastly, i've added CompatHelper and TagBot.

i think this is ready to go!

**Comment by bjarthur** [comment]
oh, and i removed REQUIRE as that is only needed for julia 0.6.

lastly, should we tag a new release?

**Comment by pkofod** [comment]
Yes, Thanks !

**Pull request merged**
