### PR TITLE
fix for Optim fde614afc161c919e4e40dc333c6a511d55ce4f8

### PR DESCRIPTION
**Pull request by bjarthur**
title says it all

### CODE REVIEW

**Comment by bjarthur** [comment]
cc @andreasnoack 

tests for this PR will fail until Optim.jl is tagged.  they pass locally though with master of Optim.jl checkout out.

this PR is a fix for https://github.com/JuliaNLSolvers/Optim.jl/commit/fde614afc161c919e4e40dc333c6a511d55ce4f8

**Comment by andreasnoack** [comment]
LGTM. Why is it that `LsqFit` has a separate implementation?

**Comment by blakejohnson** [comment]
@andreasnoack we're in the middle of an incomplete process of removing Levenberg-Marquardt from Optim.

**Comment by bjarthur** [comment]
is the plan to hold off on merging the three recent PRs until LM has been completely removed from Optim?

**Comment by pkofod** [comment]
Only if lsqfit plans to tag soon

**Comment by blakejohnson** [comment]
@pkofod the most recent tag is pretty recent. What are you hoping to still get into a tagged release of LsqFit?

**Comment by pkofod** [comment]
> @pkofod the most recent tag is pretty recent. What are you hoping to still get into a tagged release of LsqFit?

I'm not sure I'm following. @bjarthur asked if this would have to wait until Optim got rid of LM completely (that would mean tagging Optim v1.0.0). The changes here do depend on master Optim being tagged. So I just said, that if LsqFit wants to tag a new version soon, then this should wait (because Optim needs to be tagged for this to work). If LsqFit does not want to tag soon, then this can be merged without problems.

**Comment by blakejohnson** [comment]
@pkofod got it. Thanks for clarifying.

**Comment by pkofod** [comment]
Sure... Let me say though, I do intend to tag v1.0.0 soon (I don't want too much unfinished business hanging over my head going into the summer and gsoc), so it shouldn't be a problem either way.

**Comment by bjarthur** [comment]
closing because this change was seemingly implemented in https://github.com/JuliaNLSolvers/LsqFit.jl/commit/4dee493bf3101ae2cbeb327bf6c955b2bd836abc

**Pull request closed without merging**
