### PR TITLE
Work in Progress: Reconstruct LsqFit

### PR DESCRIPTION
**Pull request by iewaij**
This is a work in progress PR for rebuilding `LsqFit.jl`, the main changes will be:

1. instead of using `OptimBase.jl`, `NLSolversBase.jl` will be used for constructing objectives.
2. types and abstractions will be similar to `Optim.jl`.

The benefits are:

1. same interface as `Optim.jl`. For example, to pass `x_tol`, the code will be:

```julia
curve_fit(model, tdata, ydata, p0, LsqFit.Options(x_tol = 1e-8))
```

to pass algorithm's parameter, the code will be:

```julia
curve_fit(model, tdata, ydata, p0, LevenbergMarquardt(min_step_quality = 1e-3))
```

2. abstractions for more least squares algorithms.
3. functionalities from  `NLSolversBase`, e.g. auto differentiation.

I still need fix lots of bugs and add tests, but please let me know any ideas or comments. Thanks!

### CODE REVIEW

**Comment by pkofod** [comment]
I havn't reviewed the code yet, but the description sounds great!

**Comment by stakaz** [comment]
Could you tell anything about the time plans for this reconstruction? Would be happy to see auto differentiation as the standard way for calculating the Jacobian.

**Comment by babaq** [comment]
I am also looking forward to this branch, the assess fit part is very useful to describe goodness of fit, and I am also wandering some of the metrics in `StatsBase` such as AIC and BIC would be possible for  LsqFit?

**Comment by pkofod** [comment]
ill try to have the assessment features included soon, I just don’t have too much free time these days :( I think we can conclude that this specific pr  is dead though. 

I’m pretty sure you can already use autodiff though (I think I added that already). Finite differencing is just the default because that essentially supports everything, where autodiff might fail on some things such as BLAS calls etc.

**Comment by pkofod** [comment]
> I am also looking forward to this branch, the assess fit part is very useful to describe goodness of fit, and I am also wandering some of the metrics in `StatsBase` such as AIC and BIC would be possible for LsqFit?

What parts were you referring to? I'm not going to include the R2-part for reasons mentioned many places in text books in and on the internet. But were I'm adding the `mse` function as well. The others have been added already, but may not be in the current release, and only on master.

**Comment by babaq** [comment]
@pkofod actually I was thinking about R2 or adjR2, due to a recent work, but not realized the inappropriateness of them in non-linear models.

 I read the [line](https://stat.ethz.ch/pipermail/r-help/2000-August/007778.html ) you mentioned, and roughly understand it. but in reality, January editor do ask about the goodness of fit. in this case, I am wandering how one to report goodness of fit in non-linear models? since sometime the goodness of fit is used to separate and select dataset.

**Comment by pkofod** [comment]
>  January editor do ask about the goodness of fit.

Yeah, that a shame... There's another comment by Douglas Bates somewhere where he gets into this whole R-squared for NLS being required by referees... Maybe he has time to weigh in @dmbates

**Pull request closed without merging**
