### PR TITLE
add docstring to curve_fit

### PR DESCRIPTION
**Pull request by Datseris**

### CODE REVIEW

**Comment by Datseris** [comment]
Whenever I use `LsqFit` I always have to open my browser and go to the repo page to see the order of arguments. I never remember it by heart...

This fixes that!

**Comment by pkofod** [comment]
I'll read the string when at a PC but thanks! This is very useful

**Comment by blakejohnson** [comment]
LGTM

**Comment by pkofod** [comment]
sorry I'm late to the party, but would "values of interest" or "objects of interest" be better than "interesting values"?

**Pull request merged**
