### PR TITLE
Implement coefficient of determination r2

### PR DESCRIPTION
**Pull request by KronosTheLate**
This PR adds a much-missed feature for me personally, an estimate of the coefficient of determination, also known as r squared. Hope I did not mess anything up, and that there are no problems in adding this functionality. I know that me and other students at my level, who don't know how to interpret other parameters for the goodness of fit, much appreciate the over-used parameter r squared ^_^

### CODE REVIEW

**Comment by KronosTheLate** [comment]
I have now seen from https://juliastats.org/StatsBase.jl/stable/statmodels/#StatsBase.r2 that there is a version of this function called `r2`/`r²` defined in StatsBase. I am not certain, but I think that the name of the function should be changed to agree with the established precident. Right?

**Comment by KronosTheLate** [comment]
If there is a way to compute the sum of the squares of the deviation from the mean only from a fit, without having to explicitly pass in the y-data, that would be a huge improvement. I can't think of how through.

If the StatsBase-function `mss()` could get a method for LsqFitResults, then `r2` could get one as well, and I think that would have something really nice about it. As far as I can tell, one would need a field for LsqFitResult for the y-data in order to do this. I don't however see a problem with that, but I want someone to confirm that it is a good idea, as it seems like a much bigger intervention.

**Comment by KronosTheLate** [comment]
friendly bump

**Comment by KronosTheLate** [comment]
The current error from CI is seen below:
```
 Testing Running tests...
Running tests:
 * curve_fit.jl
ERROR: LoadError: AssertionError: norm(errors - [0.017, 0.075]) < 0.01
Stacktrace:
 [1] top-level scope
   @ ~/build/JuliaNLSolvers/LsqFit.jl/test/curve_fit.jl:27
 [2] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [3] top-level scope
   @ ~/build/JuliaNLSolvers/LsqFit.jl/test/runtests.jl:14
 [4] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [5] top-level scope
   @ none:6
in expression starting at /home/travis/build/JuliaNLSolvers/LsqFit.jl/test/curve_fit.jl:1
in expression starting at /home/travis/build/JuliaNLSolvers/LsqFit.jl/test/runtests.jl:12
ERROR: Package LsqFit errored during testing
```

I don't see how my changes could affect this, and so I think that something else has gone wrong elsewhere. Not sure though, because I don't really know the tests.

**Comment by KronosTheLate** [comment]
In the last few commits, I have attempted to use the predefined `r2` function from StatsBase, as opposed to defining my own `r_squared`. This unifies the API to that found in StatsBase and GLM.

I am not sure if the docstring added to the new method will be found when typing `?r2` - some prelimenary testing indicates that it will not. I am not sure what to do about that, so input on what to do is appriciated.

**Comment by KronosTheLate** [comment]
I have now tested the code locally, and it works as expected. The docstrings even works nicely. This supports my theory that the CI test failing is not caused by my changes.

**Comment by pkofod** [comment]
I'm sorry I didn't respond earlier. 

> The current error from CI is seen below:

This is because random numbers changed on master. We need to see StableRNGs in the tests.

**Comment by pkofod** [comment]
See Douglas Bates answer here https://stat.ethz.ch/pipermail/r-help/2002-July/023461.html

> There is a good reason that an nls model fit in R does not provide
> r-squared - r-squared doesn't make sense for a general nls model.
> 
> One way of thinking of r-squared is as a comparison of the residual
> sum of squares for the fitted model to the residual sum of squares for
> a trivial model that consists of a constant only.  You cannot
> guarantee that this is a comparison of nested models when dealing with
> an nls model.  If the models aren't nested this comparison is not
> terribly meaningful.
> 
>  So the answer is that you probably don't want to do this in the first
> place.

**Comment by KronosTheLate** [comment]
So it may not be sound to calculate R2 for a generalized NonLin fit. But as far as I can see, there is nothing wrong with supplying a function for the linear case. And then the user can be warned about the problems in the documentation, or in a printed warning. This gives the user an extra tool that has been missed for several users, and gives them information and responsibily that they can handle themselves.

I personally don't like the idea of making everything idiot-proof, at the cost of functionality. The "cost", if you will, should lie on the one who abuses the functionality, not those who would use it correctly (provided good documentation about the issue that is currently missing

**Pull request closed without merging**
