### PR TITLE
Introduce doc and fix weight issues

### PR DESCRIPTION
**Pull request by iewaij**
Introduce docs. I'm not sure I fully understand the linear approximation of the non-linear functions, e.g. what are differences between the point at solution and at the best fit point, any help would be appreciated.

Also try to fix the weight issues mentioned in #70 and #69. Under the assumption that the weight is the inverse of covariance (as seen in test the weights are providided as `1 ./ yvars`), the code actually works. But same as #69, I'm also confused why there need such assumption. So I change `covar = inv(J'*fit.wt*J)` to`covar = inv(J'*fit.wt*J)*sigma_sqr`, not sure if it's a best fix, any discussion would help!

### CODE REVIEW

**Comment by pkofod** [comment]
In the future I think it may be advantageous to split up PRs according to how closely they're related. That is, one for the docs, and one for the weights in this case. The main reason is, that it'll increase the likelihood of someone reviewing the code properly.

**Comment by pkofod** [comment]
> tocovar = inv(J'*fit.wt*J)*sigma_sqr

why would that be a good idea? I mean, where does that come from. Is this something that is actually derived from something, or something that just "seemed to work" in this particular case?

**Comment by pkofod** [comment]
(ref https://www.gnu.org/software/gsl/manual/html_node/Nonlinear-Least_002dSquares-Covariance-Matrix.html )

**Comment by iewaij** [comment]
I'll issue another 2 PRs for the doc and the weights. The main problem about the weight is "how it is defined", it could be "any" weights, optimal weights `1/var(ε)`, or could let software handle both cases together. I'm writing a more detailed docs about the optimal weights in the doc, and will use another PR to discuss the other possibility of handling weights.

**Pull request closed without merging**
