### PR TITLE
Fix 0.7 deprecations

### PR DESCRIPTION
**Pull request by blakejohnson**
Will let femtocleaner try to do its best.

### CODE REVIEW

**Comment by blakejohnson** [comment]
The femtocleaner bot doesn't seem to be working at the moment, so I ran it locally and then patched up a number of residual issues. This change makes LsqFit require at least julia 0.7-alpha.

**Comment by blakejohnson** [comment]
cc @pkofod

**Comment by pkofod** [comment]
Great! I asked @iewaij to wait with tagging a v0.7 version until we tagged a version with the new features for v0.6, is that ok?

**Comment by blakejohnson** [comment]
@pkofod fine with me.

**Comment by Datseris** [comment]
Thanks for this, I'd appreciate if it gets marged and tagged.

**Comment by pkofod** [comment]
I'll talk to @iewaij and see how far he is, and make sure that we can get this shipped soon @Datseris !

**Comment by Datseris** [comment]
Thanks @pkofod I appreciate it! At the moment this is the only thing left before we can ship DynamicalSystems framework to julia 0.7.

**Comment by pkofod** [comment]
> At the moment this is the only thing left before we can ship DynamicalSystems framework to julia 0.7.

Right, it's my fault we didn't ship this earlier, so I'll make sure it gets out there soon :)

**Pull request merged**
