### PR TITLE
ensure monotonous decay

### PR DESCRIPTION
**Pull request by JakobAsslaender**
Hi everyone!
For my fits the residuum jumps up by two orders of magnitude some point, while lamdba is small. Not sure if this PR is an appropriate counter-action, but a) it works, and b) I am assuming that the algorithm should not step when it increases the residual, or should it? Maybe this fixes also issue https://github.com/JuliaNLSolvers/LsqFit.jl/issues/164 . 

Let me know what you think!
Best,
Jakob

### CODE REVIEW

**Comment by pkofod** [comment]
I had not seen this PR until now. I will look at the references, but I'd generally agree with you. If we want a non-monotonous version, we should do it properly as described in many references.

**Comment by JakobAsslaender** [comment]
Thanks, Patrick! Much appreciated!

**Comment by chriswaudby** [comment]
Still having problems with original report #164, so this looks like a good fix

**Comment by JakobAsslaender** [comment]
@pkofod : Any updates on your plans to merge this PR?

**Comment by Gkreindler** [comment]
I'd like to mention that I also found this edit useful in an application (after making the change manually). It would be useful to have this merged PR (e.g. to run on servers).

**Comment by pkofod** [comment]
This seems correct. I'm sorry for being so slow here.

**Pull request merged**
