### PR TITLE
user supplied jacobian

### PR DESCRIPTION
**Pull request by bjarthur**
this speeds up my particular use case by 3x.

not sure of the best way to expose the interface to `curve_fit`.  for the time being i just left it unchanged.

### CODE REVIEW

**Comment by bjarthur** [comment]
tests are only failing b/c of the Rmath download is stalling.

**Comment by pkofod** [comment]
Wonderful; finite differences can be really horrible sometimes. This will not only be a speed improvement, but also accuracy improvement in many cases.

**Comment by bjarthur** [comment]
another alternative to finite differences is https://github.com/johnmyleswhite/Calculus.jl/issues/94.  i can work that up into a PR if you like.  in my use case it was slower, but as you point out, likely more accurate.

any thoughts on hoisting this to the level of `curve_fit`?  the case without weights is easy.  not sure what to do with them.

**Comment by bjarthur** [comment]
updated README, and hoisted interface to `curve_fit`.

am i right in thinking that the Jacobian simply scales with the weights just like the model does?

**Comment by marcusps** [comment]
@bjarthur Re: handling weights with the Jacobian,  have a look at #45 .  If that gets merged first, it should be easy to modify your code to handle the cases with vector and matrix weights.

**Comment by blakejohnson** [comment]
@bjarthur I merged #45. Could you please fix up the merge conflicts here?

**Comment by bjarthur** [comment]
@marcusps could you please look this over re. the weights?

@blakejohnson conflicts fixed and tests have passed

**Comment by marcusps** [comment]
Sure thing — I'll take care of it over the weekend.

**Comment by pkofod** [comment]
> this speeds up my particular use case by 3x.

I see you added the new syntax to the README. Could you perhaps also add an example (the test problem for example) to show the performance increase? That would be great, as it makes it much easier for users to see *exactly* what they're supposed to do.

**Comment by pkofod** [comment]
Excellent! I have no further comments.

**Comment by bjarthur** [comment]
example added to README.  i also took the liberty to fix a couple deprecation warnings, and to reformat the leading white space in one file.

**Comment by bjarthur** [comment]
@marcusps is my handling of the weights here kosher?  would be nice to merge this PR...

**Pull request merged**
